"""
state.py — Shared State Schema
-------------------------------
This is the single source of truth for all data flowing through the pipeline.
Every node reads from this TypedDict and returns only the fields it modifies.

Key concepts:
- Annotated[list, operator.add]  → lists get APPENDED (not overwritten) when
                                   multiple nodes write to the same field
- Annotated[list, add_messages]  → smart message merging with dedup by ID
- human_feedback                 → carries the TAPO "Observation" from one
                                   HITL checkpoint into the next agent's "Thought"
"""

import operator
from typing import Annotated, Optional
from typing_extensions import TypedDict
from langgraph.graph.message import add_messages


class PipelineState(TypedDict):
    # The topic the user wants researched and written about
    topic: str

    # Search queries generated by the Research Agent
    # operator.add means each node appends to this list instead of replacing it
    search_queries: list[str]

    # Raw results from web search — appended across multiple search calls
    research_results: Annotated[list[str], operator.add]

    # The draft blog post produced by the Writer Agent
    draft_content: str

    # The final (possibly human-edited) content ready for publishing
    final_content: str

    # Tracks where we are: "started", "queries_approved", "revision_requested", etc.
    status: str

    # Carries human feedback (TAPO Observation) into the next agent's Thought step
    # This is what enables the revision loop — the writer sees WHY it was sent back
    human_feedback: Optional[str]

    # LangChain message history — add_messages handles dedup and merging
    messages: Annotated[list, add_messages]
